/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.monopoly.gui;

/**
 *
 * @author eux
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.jPanelTbalero.setPreferredSize(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelTbalero = new javax.swing.JPanel();
        lblGo = new javax.swing.JLabel();
        lblMedAve = new javax.swing.JLabel();
        lblArcaCasilla3 = new javax.swing.JLabel();
        lblBalticAve = new javax.swing.JLabel();
        lblTaxCasilla5 = new javax.swing.JLabel();
        lblFerroCasilla6 = new javax.swing.JLabel();
        lblOrientalAve = new javax.swing.JLabel();
        lblCasuCasilla8 = new javax.swing.JLabel();
        lblVermontAve = new javax.swing.JLabel();
        lblConnAve = new javax.swing.JLabel();
        lblCarcel = new javax.swing.JLabel();
        lblCharles = new javax.swing.JLabel();
        lblCompCasilla13 = new javax.swing.JLabel();
        lblStatesAve = new javax.swing.JLabel();
        lblVirgAve = new javax.swing.JLabel();
        lblFerroCasilla16 = new javax.swing.JLabel();
        lblJames = new javax.swing.JLabel();
        lblArcaCasilla18 = new javax.swing.JLabel();
        lblTennAve = new javax.swing.JLabel();
        lblNYAve = new javax.swing.JLabel();
        lblParadaLibre = new javax.swing.JLabel();
        lblKentuckyAve = new javax.swing.JLabel();
        lblCasualCasilla23 = new javax.swing.JLabel();
        lblIndianaAve = new javax.swing.JLabel();
        lbIlliAve = new javax.swing.JLabel();
        lblFerroCasilla26 = new javax.swing.JLabel();
        lblAtlAve = new javax.swing.JLabel();
        lblVentnorAve = new javax.swing.JLabel();
        lblCompCasilla29 = new javax.swing.JLabel();
        lblMarvin = new javax.swing.JLabel();
        lblIrCarcel = new javax.swing.JLabel();
        lblPacificAve = new javax.swing.JLabel();
        lblNCAve = new javax.swing.JLabel();
        lblArcaCasilla34 = new javax.swing.JLabel();
        lblPennAve = new javax.swing.JLabel();
        lblFerroCasilla36 = new javax.swing.JLabel();
        lblCasualCasilla37 = new javax.swing.JLabel();
        lblParkPlace = new javax.swing.JLabel();
        lblTaxCasilla39 = new javax.swing.JLabel();
        lblBoardwalk = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menMenu = new javax.swing.JMenu();
        itmNuevoJuego = new javax.swing.JMenuItem();
        menEdit = new javax.swing.JMenu();
        menAcerca = new javax.swing.JMenu();
        itmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelTbalero.setLayout(new java.awt.GridBagLayout());

        lblGo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGo.setText("1 GO");
        lblGo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblGo.setMaximumSize(new java.awt.Dimension(90, 20));
        lblGo.setMinimumSize(new java.awt.Dimension(90, 20));
        lblGo.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblGo, gridBagConstraints);

        lblMedAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedAve.setText("2 Mediterranean Ave. ");
        lblMedAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMedAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblMedAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblMedAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblMedAve, gridBagConstraints);

        lblArcaCasilla3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArcaCasilla3.setText("3 Arca Común");
        lblArcaCasilla3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblArcaCasilla3.setMaximumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla3.setMinimumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla3.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblArcaCasilla3, gridBagConstraints);

        lblBalticAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalticAve.setText("4 Bastic Ave.");
        lblBalticAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBalticAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblBalticAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblBalticAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblBalticAve, gridBagConstraints);

        lblTaxCasilla5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaxCasilla5.setText("5 Impuestos");
        lblTaxCasilla5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTaxCasilla5.setMaximumSize(new java.awt.Dimension(90, 20));
        lblTaxCasilla5.setMinimumSize(new java.awt.Dimension(90, 20));
        lblTaxCasilla5.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblTaxCasilla5, gridBagConstraints);

        lblFerroCasilla6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFerroCasilla6.setText("6 Ferrocarril Reading");
        lblFerroCasilla6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFerroCasilla6.setMaximumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla6.setMinimumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla6.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblFerroCasilla6, gridBagConstraints);

        lblOrientalAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrientalAve.setText("7 Oriental Ave.");
        lblOrientalAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblOrientalAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblOrientalAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblOrientalAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblOrientalAve, gridBagConstraints);

        lblCasuCasilla8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasuCasilla8.setText("8 Casualidad");
        lblCasuCasilla8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCasuCasilla8.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCasuCasilla8.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCasuCasilla8.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCasuCasilla8, gridBagConstraints);

        lblVermontAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVermontAve.setText("9 Vermont Ave.");
        lblVermontAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVermontAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblVermontAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblVermontAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblVermontAve, gridBagConstraints);

        lblConnAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnAve.setText("10 Connecticut Ave.");
        lblConnAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblConnAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblConnAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblConnAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblConnAve, gridBagConstraints);

        lblCarcel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarcel.setText("11 Visita/Carcel");
        lblCarcel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCarcel.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCarcel.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCarcel.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCarcel, gridBagConstraints);

        lblCharles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCharles.setText("12 St. Charles Place");
        lblCharles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCharles.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCharles.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCharles.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCharles, gridBagConstraints);

        lblCompCasilla13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompCasilla13.setText("13 Compañía Electrica");
        lblCompCasilla13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCompCasilla13.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCompCasilla13.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCompCasilla13.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCompCasilla13, gridBagConstraints);

        lblStatesAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatesAve.setText("14 States Ave.");
        lblStatesAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblStatesAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblStatesAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblStatesAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblStatesAve, gridBagConstraints);

        lblVirgAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVirgAve.setText("15 Virginia Ave");
        lblVirgAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVirgAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblVirgAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblVirgAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblVirgAve, gridBagConstraints);

        lblFerroCasilla16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFerroCasilla16.setText("16 Ferrocarril Pennsylvania");
        lblFerroCasilla16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFerroCasilla16.setMaximumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla16.setMinimumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla16.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblFerroCasilla16, gridBagConstraints);

        lblJames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJames.setText("17 St. James Place");
        lblJames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblJames.setMaximumSize(new java.awt.Dimension(90, 20));
        lblJames.setMinimumSize(new java.awt.Dimension(90, 20));
        lblJames.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblJames, gridBagConstraints);

        lblArcaCasilla18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArcaCasilla18.setText("18 Arca Común");
        lblArcaCasilla18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblArcaCasilla18.setMaximumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla18.setMinimumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla18.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblArcaCasilla18, gridBagConstraints);

        lblTennAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTennAve.setText("19 Tennessee Ave.");
        lblTennAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTennAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblTennAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblTennAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblTennAve, gridBagConstraints);

        lblNYAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNYAve.setText("20 New York Ave.");
        lblNYAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNYAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblNYAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblNYAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblNYAve, gridBagConstraints);

        lblParadaLibre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParadaLibre.setText("21 Parada Libre");
        lblParadaLibre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblParadaLibre.setMaximumSize(new java.awt.Dimension(90, 20));
        lblParadaLibre.setMinimumSize(new java.awt.Dimension(90, 20));
        lblParadaLibre.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblParadaLibre, gridBagConstraints);

        lblKentuckyAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKentuckyAve.setText("22 Kentucky Ave.");
        lblKentuckyAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblKentuckyAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblKentuckyAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblKentuckyAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblKentuckyAve, gridBagConstraints);

        lblCasualCasilla23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasualCasilla23.setText("23 Casualidad");
        lblCasualCasilla23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCasualCasilla23.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCasualCasilla23.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCasualCasilla23.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCasualCasilla23, gridBagConstraints);

        lblIndianaAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndianaAve.setText("24 Indiana Ave.");
        lblIndianaAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblIndianaAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblIndianaAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblIndianaAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblIndianaAve, gridBagConstraints);

        lbIlliAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIlliAve.setText("25 Illinois Ave.");
        lbIlliAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbIlliAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lbIlliAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lbIlliAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lbIlliAve, gridBagConstraints);

        lblFerroCasilla26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFerroCasilla26.setText("26 Ferrocarril B&Q");
        lblFerroCasilla26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFerroCasilla26.setMaximumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla26.setMinimumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla26.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblFerroCasilla26, gridBagConstraints);

        lblAtlAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtlAve.setText("27 Atlantic Ave.");
        lblAtlAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAtlAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblAtlAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblAtlAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblAtlAve, gridBagConstraints);

        lblVentnorAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentnorAve.setText("28 Ventnor Ave.");
        lblVentnorAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVentnorAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblVentnorAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblVentnorAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblVentnorAve, gridBagConstraints);

        lblCompCasilla29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompCasilla29.setText("29 Compañía Agua");
        lblCompCasilla29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCompCasilla29.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCompCasilla29.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCompCasilla29.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCompCasilla29, gridBagConstraints);

        lblMarvin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarvin.setText("30 Marvin Gardens");
        lblMarvin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMarvin.setMaximumSize(new java.awt.Dimension(90, 20));
        lblMarvin.setMinimumSize(new java.awt.Dimension(90, 20));
        lblMarvin.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblMarvin, gridBagConstraints);

        lblIrCarcel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIrCarcel.setText("31 Ir a la Carcel");
        lblIrCarcel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblIrCarcel.setMaximumSize(new java.awt.Dimension(90, 20));
        lblIrCarcel.setMinimumSize(new java.awt.Dimension(90, 20));
        lblIrCarcel.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblIrCarcel, gridBagConstraints);

        lblPacificAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPacificAve.setText("32 Pacific Ave.");
        lblPacificAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPacificAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblPacificAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblPacificAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblPacificAve, gridBagConstraints);

        lblNCAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNCAve.setText("33 North Carolina Ave.");
        lblNCAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNCAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblNCAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblNCAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblNCAve, gridBagConstraints);

        lblArcaCasilla34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArcaCasilla34.setText("34 Arca Común");
        lblArcaCasilla34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblArcaCasilla34.setMaximumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla34.setMinimumSize(new java.awt.Dimension(90, 20));
        lblArcaCasilla34.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblArcaCasilla34, gridBagConstraints);

        lblPennAve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPennAve.setText("35 Pennsylvania Ave.");
        lblPennAve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPennAve.setMaximumSize(new java.awt.Dimension(90, 20));
        lblPennAve.setMinimumSize(new java.awt.Dimension(90, 20));
        lblPennAve.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblPennAve, gridBagConstraints);

        lblFerroCasilla36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFerroCasilla36.setText("36 Ferrocarril Short Line");
        lblFerroCasilla36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFerroCasilla36.setMaximumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla36.setMinimumSize(new java.awt.Dimension(90, 20));
        lblFerroCasilla36.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblFerroCasilla36, gridBagConstraints);

        lblCasualCasilla37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasualCasilla37.setText("37 Casualidad");
        lblCasualCasilla37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCasualCasilla37.setMaximumSize(new java.awt.Dimension(90, 20));
        lblCasualCasilla37.setMinimumSize(new java.awt.Dimension(90, 20));
        lblCasualCasilla37.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblCasualCasilla37, gridBagConstraints);

        lblParkPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParkPlace.setText("38 Park Place");
        lblParkPlace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblParkPlace.setMaximumSize(new java.awt.Dimension(90, 20));
        lblParkPlace.setMinimumSize(new java.awt.Dimension(90, 20));
        lblParkPlace.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblParkPlace, gridBagConstraints);

        lblTaxCasilla39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaxCasilla39.setText("39 Impuestos");
        lblTaxCasilla39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTaxCasilla39.setMaximumSize(new java.awt.Dimension(90, 20));
        lblTaxCasilla39.setMinimumSize(new java.awt.Dimension(90, 20));
        lblTaxCasilla39.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblTaxCasilla39, gridBagConstraints);

        lblBoardwalk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBoardwalk.setText("40 Boardwalk");
        lblBoardwalk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBoardwalk.setMaximumSize(new java.awt.Dimension(90, 20));
        lblBoardwalk.setMinimumSize(new java.awt.Dimension(90, 20));
        lblBoardwalk.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTbalero.add(lblBoardwalk, gridBagConstraints);

        menMenu.setText("Menu");

        itmNuevoJuego.setText("Nuevo Juego");
        menMenu.add(itmNuevoJuego);

        jMenuBar1.add(menMenu);

        menEdit.setText("Edit");
        jMenuBar1.add(menEdit);

        menAcerca.setText("Acerca");

        itmAcerca.setText("Acerca de Monopoly");
        menAcerca.add(itmAcerca);

        jMenuBar1.add(menAcerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTbalero, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelTbalero, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAcerca;
    private javax.swing.JMenuItem itmNuevoJuego;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelTbalero;
    private javax.swing.JLabel lbIlliAve;
    private javax.swing.JLabel lblArcaCasilla18;
    private javax.swing.JLabel lblArcaCasilla3;
    private javax.swing.JLabel lblArcaCasilla34;
    private javax.swing.JLabel lblAtlAve;
    private javax.swing.JLabel lblBalticAve;
    private javax.swing.JLabel lblBoardwalk;
    private javax.swing.JLabel lblCarcel;
    private javax.swing.JLabel lblCasuCasilla8;
    private javax.swing.JLabel lblCasualCasilla23;
    private javax.swing.JLabel lblCasualCasilla37;
    private javax.swing.JLabel lblCharles;
    private javax.swing.JLabel lblCompCasilla13;
    private javax.swing.JLabel lblCompCasilla29;
    private javax.swing.JLabel lblConnAve;
    private javax.swing.JLabel lblFerroCasilla16;
    private javax.swing.JLabel lblFerroCasilla26;
    private javax.swing.JLabel lblFerroCasilla36;
    private javax.swing.JLabel lblFerroCasilla6;
    private javax.swing.JLabel lblGo;
    private javax.swing.JLabel lblIndianaAve;
    private javax.swing.JLabel lblIrCarcel;
    private javax.swing.JLabel lblJames;
    private javax.swing.JLabel lblKentuckyAve;
    private javax.swing.JLabel lblMarvin;
    private javax.swing.JLabel lblMedAve;
    private javax.swing.JLabel lblNCAve;
    private javax.swing.JLabel lblNYAve;
    private javax.swing.JLabel lblOrientalAve;
    private javax.swing.JLabel lblPacificAve;
    private javax.swing.JLabel lblParadaLibre;
    private javax.swing.JLabel lblParkPlace;
    private javax.swing.JLabel lblPennAve;
    private javax.swing.JLabel lblStatesAve;
    private javax.swing.JLabel lblTaxCasilla39;
    private javax.swing.JLabel lblTaxCasilla5;
    private javax.swing.JLabel lblTennAve;
    private javax.swing.JLabel lblVentnorAve;
    private javax.swing.JLabel lblVermontAve;
    private javax.swing.JLabel lblVirgAve;
    private javax.swing.JMenu menAcerca;
    private javax.swing.JMenu menEdit;
    private javax.swing.JMenu menMenu;
    // End of variables declaration//GEN-END:variables
}
